Es6 promises
le-andre/rc0522-code-solutions pull request #94
Opened 2022-07-08 20:08 UTC by le-andre

![image](https://user-images.githubusercontent.com/103016667/178063220-f1f1f7ea-7700-44d2-bb98-8b72e2727434.png)

2022-07-08 20:16 UTC, TimelikeClosure requested changes

2022-07-08 20:16 UTC, TimelikeClosure commented on es6-promises/index.js
> +});
Make sure only the message shows, not the whole `Error` object.

---

![image](https://user-images.githubusercontent.com/16143771/178063593-9e880e3c-4d38-45ce-b0e3-de13ceb2ca6e.png)

2022-07-11 22:08 UTC, scbowler requested changes
Looking good, but one update needed. Let me know if you have any questions.

2022-07-11 22:34 UTC, scbowler approved these changes
Great job implementing the feedback, looks good! 👍

2022-07-11 22:35 UTC, merged